name: "✨ 기능 추가 (Feature)"
description: "새로운 기능이나 컴포넌트를 개발할 때 사용합니다."
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "🚀 작업 내용"
      description: "어떤 기능을 구현하는지 명확하게 적어주세요."
      placeholder: "예: 로그인 페이지 비밀번호 표시/숨기기 기능 추가"
    validations:
      required: true