name: "🐛 버그 수정 (Fix)"
description: "애플리케이션의 오류를 수정할 때 사용합니다."
title: "[Fix]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug_report
    attributes:
      label: "🛠 버그 현상 및 수정 계획"
      description: "어떤 버그가 발생했고, 어떻게 수정할 예정인지 적어주세요."
      placeholder: "예: Safari 브라우저에서 헤더 그림자가 깨지는 현상 수정"
    validations:
      required: true