name: "🎨 디자인 변경 (Design)"
description: "스타일링 수정이나 UI 디자인 변경 시 사용합니다."
title: "[Design]: "
labels: ["design"]
body:
  - type: textarea
    id: design_change
    attributes:
      label: "💎 디자인 수정 내용"
      description: "어떤 시각적 요소가 바뀌는지 적어주세요."
      placeholder: "예: 메인 테마 색상을 Indigo로 변경"
    validations:
      required: true