name: "📝 문서 수정 (Docs)"
description: "README, 문서, 주석 등을 수정할 때 사용합니다."
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: docs_change
    attributes:
      label: "📚 수정 문서 내용"
      placeholder: "예: 프로젝트 설치 가이드 문구 수정"
    validations:
      required: true