name: "🔧 기타/설정 (Chore)"
description: "패키지 관리, 빌드 설정, 단순 오타 수정 등 기타 작업을 수행합니다."
title: "[Chore]: "
labels: ["chore"]
body:
  - type: textarea
    id: chore_details
    attributes:
      label: "⚙️ 작업 상세"
      placeholder: "예: package.json 라이브러리 버전 업데이트"
    validations:
      required: true