import type { Metadata } from 'next';
import { Poppins, Noto_Sans_KR } from 'next/font/google';
import './styles/base.css';
import { Providers } from './provider/providers';
import { SidebarProvider } from '@repo/ui/components/sidebar';
import { MainHeader } from '@/widgets/main-header';
import { MainSidebar } from '@/widgets/main-sidebar';
import { MainFooter } from '@/widgets/main-footer';
import { PrefetchCrossZoneLinks } from '@vercel/microfrontends/next/client';

const notoSansKr = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: '井에서의 개발일지',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${notoSansKr.className} ${notoSansKr.variable} ${poppins.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider defaultOpen={false} className="flex-col">
            <MainHeader />
            <MainSidebar />
            {children}
            <MainFooter />
          </SidebarProvider>
        </Providers>
        <PrefetchCrossZoneLinks />
      </body>
    </html>
  );
}
